version: '3'
services:
 ms-sql-server:
  image: mcr.microsoft.com/mssql/server:2022-latest
  environment: 
   - ACCEPT_EULA=Y
   - SA_PASSWORD=BilliJin2000
   - MSSQL_PID=Express
  ports: 
   - "1433:1433"
 weather-forecast-api:
  build: .
  environment: 
   - DbServer=ms-sql-server
  ports:
   - "8080:80"